FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR ./

COPY . .
RUN dotnet publish -c Release -o /publish


FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=build /publish .


EXPOSE 80

ENTRYPOINT ["dotnet", "pokemon-seeker.dll"]
