FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copia os arquivos
COPY . .

# Publica diretamente o projeto principal
RUN dotnet publish Pokemon-seeker.presentation/Pokemon-seeker.presentation.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 80

ENTRYPOINT ["dotnet", "Pokemon-seeker.presentation.dll"]
